Repository seoyeon-1206/JS-team11-project, pull requests merged in 2024-01, with the labels that each got.

#3 Feat detail.html생성/#2
  detail.html
  index.html
Labels: enhancement, question

#8 [Feat/#7] review 조회 기능 파일 reviewRead.js 생성 및 필요한 div 요소와 클래스 추가
  detail.html
  src/reviewRead.js
Labels: documentation, enhancement

#14 [ Feat ] - review기능에서 div 속성을 querySelector로 찾기 위해 클래스 추가
  detail.html
  src/data.js
  src/reviewRead.js
Labels: documentation

#16 [Feat/#15] reviewDel.js 생성 및 data.js파일 삭제
  src/data.js
  src/reviewDel.js
Labels: documentation, enhancement

#17 [Feat] - deatil.js 생성
  detail.html
  src/detail.js
Labels: documentation, enhancement

#26 [Feat] - detail.css생성
  css/color.css
  css/detail.css
  css/index.css
  detail.html
  src/detail.js
Labels: style

#28 [Feat] review 삭제 기능 테스트 ing
  src/reviewDel.js
  src/reviewRead.js
  src/reviewReg.js
Labels: documentation

#32 [Feat] moveId 가져오는 속성 pathname => search
  src/reviewDel.js
  src/reviewRead.js
Labels: documentation

#37 Style review css#27
  css/detail.css
  detail.html
  src/reviewRead.js
Labels: style

#40 [Feat] review 삭제 기능 수정 중
  src/items/reviewReadTemp.js
  src/movie.js
  src/reviewDel.js
  src/reviewRead.js
  src/reviewReg.js
Labels: bug, documentation

#43 [Fix] - review 등록, 조회 부분 새로고침 문제들 해결 #41
  src/items/reviewReadTemp.js
  src/reviewDel.js
  src/reviewRead.js
  src/reviewReg.js
Labels: documentation

#45 [Del] - reviewDel.js 삭제 및 [Feat] 해당 기능의 CSS class 수정 / 파일이름 변경 및 review 등록,삭제 코드 결합
  css/detail.css
  detail.html
  src/items/reviewReadTemp.js
  src/reviewDel.js
  src/reviewRead.js
  src/reviewReadValues.js
  src/reviewReg.js
Labels: documentation, enhancement

#51 [Feat] 날짜 추가, 틀어진 리뷰 조회 부분 CSS 복구, 변경된 템플릿 구조에 따라 css 일부 id속성에서 class속성으로 변경
  css/detail.css
  src/common/reviewReadTemp.js
  src/reviewReg.js
Labels: documentation, enhancement

#53 [Feat/#49] 템플릿 div -class : read-id 개별 분리
  src/common/reviewReadTemp.js
  src/reviewReg.js
Labels: bug, documentation, enhancement

#57 [Feat] - detail.css style 수정
  css/detail.css
  src/common/reviewReadTemp.js
Labels: style

#58 [Fix] - 쿼리스트링으로 영화 id 가져오는 방법 변경 #56
  src/reviewReg.js
Labels: bug, documentation, enhancement

#65 Style review css#27
  css/detail.css
  css/index.css
  src/common/reviewReadTemp.js
Labels: style
